name: tripora
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  table_calendar: ^3.2.0
  lucide_icons: ^0.257.0
  animated_background: ^2.0.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
        

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/exp_genting.png
    - assets/images/exp_penang.png
    - assets/images/exp_johor.png
    - assets/images/exp_kl2.png
    - assets/images/exp_msia.png
    - assets/images/exp_kinabalu.png
    - assets/images/exp_kl.png
    - assets/images/kl_towers.png
    - assets/images/exp_profile_picture.png
    - assets/images/exp_melaka_trip.png
    - assets/images/exp_melaka.png
    - assets/images/exp_semporna.png
    - assets/icons/city.png
    - assets/icons/museum.png
    - assets/icons/nature.png
    - assets/icons/restaurant.png
    - assets/images/exp_location.png
    - assets/images/exp_nearby1.png
    - assets/images/exp_nearby2.png
    - assets/images/exp_nearby3.png
    - assets/images/exp_nearby4.png
    - assets/icons/distance.png
    - assets/icons/distance_white.png
    - assets/images/exp_map.png
    - assets/images/itinerary/sunway_university.png
    - assets/images/itinerary/stadthuys.png
    - assets/images/itinerary/peranakan_place.png
    - assets/images/itinerary/tan_kim_hock.png
    - assets/images/itinerary/mamee.png
    - assets/images/destination_selection/johor.png
    - assets/images/destination_selection/kedah.png
    - assets/images/destination_selection/kelantan.png
    - assets/images/destination_selection/kl.png
    - assets/images/destination_selection/labuan.png
    - assets/images/destination_selection/melaka.png
    - assets/images/destination_selection/negeri_sembilan.png
    - assets/images/destination_selection/pahang.png
    - assets/images/destination_selection/penang.png
    - assets/images/destination_selection/perak.png
    - assets/images/destination_selection/perlis.png
    - assets/images/destination_selection/putrajaya.png
    - assets/images/destination_selection/sabah.png
    - assets/images/destination_selection/sarawak.png
    - assets/images/destination_selection/selangor.png
    - assets/images/destination_selection/terengganu.png
    - assets/images/travel_style/adventure_outdoor.png
    - assets/images/travel_style/cultural_historical.png
    - assets/images/travel_style/food_culinary.png
    - assets/images/travel_style/leisure_relaxation.png
    - assets/images/travel_style/nature.png
    - assets/images/travel_style/urban_exploration.png
    - assets/images/travel_partner/solo.png
    - assets/images/travel_partner/couple.png
    - assets/images/travel_partner/family.png
    - assets/images/travel_partner/friends.png
    - assets/images/travel_partner/business.png
    - assets/images/travel_partner/group_tour.png
    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
